City-of-Helsinki/huvaja

- app/pages/resource/info/ResourceInfo.js
- app/pages/resource/info/ResourceInfo.spec.js
- app/pages/resource/info/resource-info.less
> Add equipment to resource info (refs #33)

- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/pages/resource/ResourcePageContainer.js
- app/pages/resource/ResourcePageContainer.spec.js
- app/pages/resource/resourcePageSelector.js
- app/pages/resource/resourcePageSelector.spec.js
- app/pages/search/SearchPageContainer.js
- app/shared/availability-view/AvailabilityView.js
- app/shared/availability-view/AvailabilityView.spec.js
- app/shared/availability-view/DateSelector.js
- app/shared/availability-view/DateSelector.spec.js
- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.spec.js
- app/shared/availability-view/availability-view.less
- app/state/reducers/index.js
- app/state/reducers/resourcePageReducer.js
- app/state/reducers/resourcePageReducer.spec.js
> Resource page timeline

- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/pages/resource/SelectableSingleAvailabilityView.js
- app/pages/resource/SelectableSingleAvailabilityView.spec.js
- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js
- app/shared/availability-view/availability-view.less
- app/shared/availability-view/index.js
Closes #36.
There's a couple of things in that issue that I didn't do here, as I think it could make sense to do them as a part of other issues.
- There's currently no way for the ResourcePage component to get the selection from the SelectableSingleAvailabilityView component. I'm not sure what'd be the best way for it to get it, so that could be added in #37 which is the issue that needs the selection info.
- I also didn't remove the reserve=true parameter yet. It seems like it'll be useless, but it kind of depends on how showing the reservation form will be done exactly. So that could be done as a part of #40.
> Select reservation time

- app/auth/reducer.js
- app/auth/reducer.spec.js
- app/pages/AppContainer.js
- app/pages/AppContainer.spec.js
> Render AppContainer children after Auth is fetched

- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/ReservationForm.spec.js
- app/pages/resource/reservation-form/ReservationFormContainer.js
- app/pages/resource/reservation-form/ReservationFormContainer.spec.js
- app/shared/form-fields/ReduxFormField.js
- app/shared/form-fields/ReduxFormField.spec.js
- app/shared/form-fields/reservation-time/ReservationTime.js
- app/shared/form-fields/reservation-time/ReservationTime.spec.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.spec.js
- app/shared/form-fields/reservation-time/index.js
Part of #37. The changes that have been done here are the ones that'll affect #40. The remaining part is just about showing submit success / failure, i.e. non-blocking changes, so those can be merged in another PR to get rid of the block more quickly.
> Post reservation

- app/api/actions/reservations.js
- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/ReservationFormContainer.js
- app/pages/resource/reservation-form/ReservationFormContainer.spec.js
- app/state/middleware/index.js
- app/state/middleware/sideEffects.js
- app/state/middleware/sideEffects.spec.js
- app/utils/createFormSubmitHandler.js
- app/utils/createFormSubmitHandler.spec.js
Closes #37.
Things that'll happen when the form is submitted successfully (showing the reservation modal and closing the form) will be done once those pieces of functionality are been implemented.
> Post reservation effects

- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/ReservationForm.spec.js
- app/pages/resource/reservation-form/ReservationFormContainer.js
- app/state/reducers/formPlugins.js
- app/state/reducers/formPlugins.spec.js
- app/state/reducers/index.js
> Hide reservation form

- app/shared/availability-view/AvailabilityView.js
- app/shared/availability-view/AvailabilityView.spec.js
- app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.js
- app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.spec.js
- app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.js
- app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.spec.js
- app/shared/availability-view/Sidebar/Sidebar.js
- app/shared/availability-view/Sidebar/Sidebar.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
- app/shared/availability-view/availability-view.less
- app/state/reducers/resourcePageReducer.js
- app/state/reducers/resourcePageReducer.spec.js
> Dates in resource links

- app/pages/resource/resource-page.less
> Fix resouce page resource info style definition

- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.spec.js
> Fix removing time selection on submit

- app/state/reducers/cateringReducer.js
- app/state/reducers/cateringReducer.spec.js
> Clear catering data after successful reservation

- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Link.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.js
- app/shared/availability-view/availability-view.less
- package.json
> Drag to scroll

- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.js
> Initial timeline scroll

- app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.js
- app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.js
- app/shared/availability-view/availability-view.less
> Improve narrow screen styles

- app/pages/AppContainer.js
- app/pages/AppContainer.spec.js
- app/utils/locationUtils.js
> Automatic and required login

- app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.spec.js
- app/shared/availability-view/availability-view.less
- app/shared/availability-view/index.js
- package.json
> Sticky time row

- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.spec.js
- app/shared/availability-view/availability-view.less
- package.json
> Show line for current time

- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
> No sticky hours on resource page

- app/actions/uiActions.js
- app/pages/AppContainer.js
- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/pages/resource/ResourcePageContainer.js
- app/pages/resource/ResourcePageContainer.spec.js
- app/pages/resource/info/ResourceInfo.js
- app/pages/resource/info/ResourceInfo.spec.js
- app/pages/resource/info/resource-info.less
- app/pages/resource/resource-page.less
- app/pages/resource/resourcePageSelector.js
- app/pages/resource/resourcePageSelector.spec.js
- app/shared/favorite-button/favorite-button.less
- app/shared/image-carousel/image-carousel.less
- app/shared/modals/resource-images/ResourceImages.js
- app/shared/modals/resource-images/ResourceImages.spec.js
- app/shared/modals/resource-images/ResourceImagesContainer.js
- app/shared/modals/resource-images/index.js
- app/shared/modals/resource-images/resourceImagesSelector.js
- app/state/reducers/index.js
- app/state/reducers/resourceImagesModalReducer.js
- app/state/reducers/resourceImagesModalReducer.spec.js
> Improve top of resource page

- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/ReservationForm.spec.js
- app/pages/resource/reservation-form/ReservationFormContainer.js
- app/pages/resource/reservation-form/ReservationFormContainer.spec.js
- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
> Event description

- app/api/actionTypes.js
- app/api/actions/equipment.js
- app/api/actions/equipment.spec.js
- app/api/actions/index.js
- app/api/actions/schemas.js
- app/api/actions/types.js
- app/api/actions/types.spec.js
- app/api/reducers/dataReducer.js
- app/index.js
- app/pages/AppContainer.js
- app/pages/AppContainer.spec.js
- app/pages/search/SearchPageContainer.js
- app/pages/search/SearchPageContainer.spec.js
- app/pages/search/search-controls/SearchControls.js
- app/pages/search/search-controls/SearchControls.spec.js
- app/pages/search/search-controls/search-controls.less
- app/pages/search/searchPageSelector.js
- app/pages/search/searchPageSelector.spec.js
- app/shared/form-fields/label-select/LabelSelect.js
- app/shared/form-fields/label-select/LabelSelect.spec.js
- app/shared/form-fields/label-select/index.js
- app/shared/form-fields/label-select/label-select.less
- app/shared/shared.less
- app/state/reducers/searchFiltersReducer.js
- app/state/reducers/searchFiltersReducer.spec.js
- package.json
Closes #108 
Date time range filter ("Vapaana aikavälille") will be implemented in another branch.
> Search criteria

- app/shared/availability-view/AvailabilityView.js
- app/shared/availability-view/AvailabilityView.spec.js
- app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.js
- app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.js
- app/shared/availability-view/Sidebar/Sidebar.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroups.js
- app/shared/availability-view/availability-view.less
> Add hover effect to resource row

- app/actions/uiActions.js
- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/pages/resource/ResourcePageContainer.js
- app/pages/resource/ResourcePageContainer.spec.js
- app/pages/resource/info/ResourceInfo.js
- app/pages/resource/info/ResourceInfo.spec.js
- app/pages/resource/resourcePageSelector.js
- app/pages/resource/resourcePageSelector.spec.js
- app/pages/search/SearchPageContainer.js
- app/pages/search/SearchPageContainer.spec.js
- app/pages/search/search-controls/SearchControls.js
- app/pages/search/search-controls/SearchControls.spec.js
- app/state/reducers/searchFiltersReducer.js
- app/state/reducers/searchFiltersReducer.spec.js
- app/utils/locationUtils.js
- app/utils/locationUtils.spec.js
> Automatic search

- app/pages/search/search-controls/search-controls.less
- app/shared/form-fields/form-fields.less
Closes #124 
The review app redirects to huvaja-staging.herokuapp.com so I was not able to test this properly in Browserstack's IE 11. However, when I made the same style changes in debugger, they seemed to fix the problems.
> Date field fixes for IE

- config/make-karma-config.js
Shows diffs of expected and actual values on failed tests.
Closes #129
> Improve karma test configs

- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePageContainer.js
- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/ReservationForm.spec.js
- app/pages/resource/reservation-form/ReservationFormContainer.js
- app/pages/resource/reservation-form/ReservationFormContainer.spec.js
- app/shared/availability-view/SingleAvailabilityView.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Link.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.spec.js
- app/shared/form-fields/DateTimeRange.js
- app/shared/form-fields/DateTimeRange.spec.js
- app/shared/form-fields/Time.js
- app/shared/form-fields/form-fields.less
- app/shared/form-fields/reservation-time/ReservationTime.spec.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.spec.js
- app/state/reducers/formPlugins.js
- app/state/reducers/formPlugins.spec.js
> Time fields to reservation form

- app/assets/styles/variables.less
- app/pages/resource/reservation-form/ReservationForm.js
- app/pages/resource/reservation-form/reservation-form.less
- app/pages/search/search-controls/search-controls.less
> Update reservation form participant count styles

- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js
- app/shared/availability-view/availability-view.less
> Color open slots

- app/assets/styles/variables.less
> Make participant count wider

- app/api/actionTypes.js
- app/api/actions/comments.js
- app/api/actions/comments.spec.js
- app/api/actions/createApiAction.js
- app/api/actions/index.js
- app/api/reducers/dataReducer.js
- app/shared/comments/Comments.js
- app/shared/comments/Comments.spec.js
- app/shared/comments/CommentsContainer.js
- app/shared/comments/CommentsContainer.spec.js
- app/shared/comments/comments.less
- app/shared/comments/index.js
- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
- app/shared/shared.less
> Show mock reservation comments

- app/api/actionTypes.js
- app/api/actions/comments.js
- app/api/actions/comments.spec.js
- app/api/actions/index.js
- app/api/reducers/dataReducer.js
- app/shared/comments/CommentAdder.js
- app/shared/comments/CommentAdder.spec.js
- app/shared/comments/CommentForm.js
- app/shared/comments/CommentForm.spec.js
- app/shared/comments/Comments.js
- app/shared/comments/Comments.spec.js
- app/shared/comments/CommentsContainer.js
- app/shared/comments/CommentsContainer.spec.js
- app/shared/comments/comments.less
- app/state/reducers/formPlugins.js
- app/state/reducers/formPlugins.spec.js
Closes #142.
Merge #143 first.
> Create reservation comments

- app/api/actions/comments.js
- app/api/actions/comments.spec.js
- app/api/reducers/dataReducer.js
- app/shared/comments/CommentsContainer.js
- app/shared/comments/CommentsContainer.spec.js
Closes #157.
Merge #156 first.
> Create catering comments

- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
> Only render cancel button if user has rights

- app/shared/reservation-form/EditReservationFormContainer.js
- app/shared/reservation-form/EditReservationFormContainer.spec.js
> Add edit reservation form container

- app/pages/reservationSearch/ReservationSearchPageContainer.spec.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRow.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRow.spec.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRowContainer.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRowContainer.spec.js
- app/pages/reservationSearch/day-reservations/reservation-row/reservation-row.less
- app/pages/reservationSearch/day-reservations/reservation-row/reservationRowSelector.js
- app/pages/reservationSearch/day-reservations/reservation-row/reservationRowSelector.spec.js
- app/pages/reservationSearch/reservation-search-controls/ReservationSearchControls.js
- app/pages/reservationSearch/reservation-search-controls/ReservationSearchControls.spec.js
- app/pages/reservationSearch/reservationSearchPageSelector.spec.js
- app/shared/modals/reservation-info/ReservationInfo.js
- app/state/reducers/reservationSearchFiltersReducer.js
- app/state/reducers/reservationSearchFiltersReducer.spec.js
> Improve reservations page

- app/index.js
- package.json
> Scroll up when page changes

- app/shared/image-carousel/ImageCarousel.js
> Preload images on carousel

- app/pages/reservationCreate/ReservationCreatePageContainer.js
- app/pages/reservationCreate/ReservationCreatePageContainer.spec.js
- app/pages/resource/ResourcePage.js
- app/pages/resource/ResourcePage.spec.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.js
- app/shared/form-fields/reservation-time/SelectableSingleAvailabilityView.spec.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationCreateFormContainer.spec.js
> Use SelectableSingleAvailabilityView in ResourcePage

- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRow.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRowContainer.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js
- app/shared/modals/reservation-info/ReservationInfo.js
> Handle null values for numberOfParticipants

- app/api/actions/comments.js
- app/api/actions/comments.spec.js
- app/api/reducers/dataReducer.js
- app/shared/comments/CommentForm.js
- app/shared/comments/CommentForm.spec.js
- app/shared/comments/Comments.js
- app/shared/comments/Comments.spec.js
- app/shared/comments/CommentsContainer.js
- app/shared/comments/CommentsContainer.spec.js
> Use real API for reservation comments

- app/shared/comments/Comments.js
- app/shared/comments/Comments.spec.js
- app/shared/comments/FormattedUserText.js
- app/shared/comments/FormattedUserText.spec.js
> Show paragraphs and line changes in comments

- app/shared/reservation-form/catering/catering-form/CateringFormContainer.js
- app/shared/reservation-form/catering/catering-form/CateringFormContainer.spec.js
> Make project number required in catering form

- app/shared/reservation-form/catering/catering-form/CateringFormContainer.js
> Fix catering form

- app/shared/reservation-form/catering/catering-form/CateringFormContainer.js
- app/shared/reservation-form/catering/catering-form/CateringFormContainer.spec.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.spec.js
> Fix invalid date problems

- app/assets/styles/_application-variables.scss
- app/shared/availability-view/_availability-view.scss
> Change timeline slot colors

- app/shared/form-fields/resource-field/ResourceField.js
- app/shared/form-fields/resource-field/ResourceField.spec.js
> Change button text when no resource selected

- app/shared/form-fields/resource-field/resource-selector/ResourceSelector.js
- app/shared/form-fields/resource-field/resource-selector/ResourceSelector.spec.js
- app/shared/form-fields/resource-field/resource-selector/ResourceSelectorContainer.js
- app/shared/form-fields/resource-field/resource-selector/resourceSelectorSelector.js
- app/shared/form-fields/resource-field/resource-selector/resourceSelectorSelector.spec.js
> Show one resource list if no selected time

- app/api/actionTypes.js
- app/api/actions/catering.js
- app/api/actions/catering.spec.js
- app/api/actions/index.js
- app/api/actions/schemas.js
- app/api/reducers/dataReducer.js
- app/api/selectors/createCateringProviderSelector.js
- app/api/selectors/createCateringProviderSelector.spec.js
- app/api/selectors/index.js
- app/pages/AppContainer.js
- app/pages/AppContainer.spec.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationCreateFormContainer.spec.js
- app/shared/reservation-form/ReservationEditFormContainer.js
- app/shared/reservation-form/ReservationEditFormContainer.spec.js
- app/shared/reservation-form/ReservationForm.js
- app/shared/reservation-form/ReservationForm.spec.js
- app/shared/reservation-form/catering/catering-form/CateringFormContainer.js
- app/shared/reservation-form/catering/catering-form/CateringFormContainer.spec.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.spec.js
> Price page URL

- app/actions/recurringReservations.js
- app/assets/styles/main.scss
- app/shared/_shared.scss
- app/shared/compact-reservation-list/CompactReservationList.js
- app/shared/compact-reservation-list/compact-reservation-list.scss
- app/shared/compact-reservation-list/index.js
- app/shared/recurring-reservation-controls/RecurringReservationControls.js
- app/shared/recurring-reservation-controls/RecurringReservationControlsContainer.js
- app/shared/recurring-reservation-controls/_recurring-reservation-controls.scss
- app/shared/recurring-reservation-controls/index.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationForm.js
- app/shared/reservation-form/_reservation-form.scss
- app/shared/time-range/TimeRange.js
- app/shared/time-range/TimeRange.spec.js
- app/shared/time-range/index.js
- app/state/middleware/createRecurringReservations.js
- app/state/middleware/index.js
- app/state/reducers/index.js
- app/state/reducers/recurringReservationsReducer.js
- app/utils/timeUtils.js
- package.json
Refs #216 
This PR includes the basic functionality for creating recurring reservations. It doesn't include for example showing whether creating succeeded and it doesn't include tests.
> Recurring reservations (part 1)

- app/pages/reservationSearch/ReservationSearchPageContainer.spec.js
- app/pages/reservationSearch/reservation-search-controls/ReservationSearchControls.js
- app/pages/reservationSearch/reservation-search-controls/ReservationSearchControls.spec.js
- app/pages/reservationSearch/reservationSearchPageSelector.spec.js
- app/state/reducers/reservationSearchFiltersReducer.js
- app/state/reducers/reservationSearchFiltersReducer.spec.js
> Enable "has catering order" filter

- app/pages/AppContainer.js
- app/pages/AppContainer.spec.js
- app/pages/_pages.scss
- app/pages/myInfo/MyInfoPage.js
- app/pages/myInfo/MyInfoPage.spec.js
- app/pages/myInfo/MyInfoPageContainer.js
- app/pages/myInfo/_my-info-page.scss
- app/pages/myInfo/index.js
- app/pages/reservationSearch/day-reservations/reservation-row/reservationRowSelector.js
- app/routes.js
- app/shared/_shared.scss
- app/shared/favorite-resources/FavoriteResources.js
- app/shared/favorite-resources/FavoriteResources.spec.js
- app/shared/favorite-resources/FavoriteResourcesContainer.js
- app/shared/favorite-resources/FavoriteResourcesContainer.spec.js
- app/shared/favorite-resources/_favorite-resources.scss
- app/shared/favorite-resources/favorite-resource/FavoriteResource.js
- app/shared/favorite-resources/favorite-resource/FavoriteResource.spec.js
- app/shared/favorite-resources/favorite-resource/_favorite-resource.scss
- app/shared/favorite-resources/favorite-resource/index.js
- app/shared/favorite-resources/favoriteResourcesSelector.js
- app/shared/favorite-resources/favoriteResourcesSelector.spec.js
- app/shared/favorite-resources/index.js
- app/shared/form-fields/resource-field/resource-selector/resourceSelectorSelector.js
- app/shared/navbar/Navbar.js
- app/shared/navbar/Navbar.spec.js
- app/utils/resourceUtils.js
- app/utils/resourceUtils.spec.js
> My info page part 1

- app/api/actions/comments.js
- app/api/actions/comments.spec.js
- app/shared/comments/CommentsContainer.js
- app/shared/comments/CommentsContainer.spec.js
- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
Closes #232 
Merge #260 first.
> Make catering comments work with API

- app/constants/AppConstants.js
- app/pages/reservationSearch/day-reservations/DayReservations.js
- app/shared/availability-view/DateSelector.js
- app/shared/availability-view/DateSelector.spec.js
- app/shared/comments/Comments.js
- app/shared/comments/Comments.spec.js
- app/shared/date-picker/DatePicker.js
- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
- app/shared/modals/reservation-info/_reservation-info.scss
- app/shared/modals/reservation-success/ReservationSuccessModal.js
- app/shared/modals/reservation-success/ReservationSuccessModal.spec.js
- app/shared/modals/resource-selector/ResourceSelectorModal.js
- app/shared/recurring-reservation-controls/RecurringReservationControls.js
- app/shared/reservation-form/ReservationForm.js
- app/shared/reservation-form/ReservationForm.spec.js
- app/shared/reservation-form/catering/catering-form/CateringMenu.js
- app/shared/time-range/TimeRange.js
> Misc small improvements

- app/api/actions/catering.spec.js
- app/api/utils.spec.js
- app/shared/form-fields/ReduxFormField.spec.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationCreateFormContainer.spec.js
- app/shared/reservation-form/ReservationForm.spec.js
- app/shared/reservation-form/catering/CateringSectionContainer.spec.js
- app/shared/reservation-form/catering/catering-form/CateringForm.spec.js
- app/shared/reservation-form/catering/catering-form/CateringFormContainer.spec.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.js
- app/shared/reservation-form/catering/catering-form/cateringFormSelector.spec.js
- app/shared/reservation-form/catering/utils.spec.js
> Catering tests

- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRow.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRow.spec.js
- app/pages/reservationSearch/day-reservations/reservation-row/ReservationRowContainer.js
- app/pages/reservationSearch/day-reservations/reservation-row/_reservation-row.scss
- app/pages/reservationSearch/day-reservations/reservation-row/reservationRowSelector.js
> Show catering icon to reservations list

- app/api/actionTypes.js
- app/api/actions/catering.js
- app/api/actions/catering.spec.js
- app/api/actions/index.js
- app/api/reducers/dataReducer.js
- app/api/reducers/dataReducer.spec.js
- app/api/selectors/index.js
- app/pages/reservationEdit/ReservationEditPageContainer.js
- app/pages/reservationEdit/ReservationEditPageContainer.spec.js
- app/pages/reservationEdit/ReservationEditPageSelector.js
- app/pages/reservationEdit/reservationEditPageSelector.spec.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationEditFormContainer.js
- app/shared/reservation-form/ReservationEditFormContainer.spec.js
- app/shared/reservation-form/catering/CateringSectionContainer.js
- app/shared/reservation-form/catering/CateringSectionContainer.spec.js
- app/shared/reservation-form/catering/catering-form/CateringForm.js
- app/state/reducers/reservationCateringOrdersReducer.js
- app/state/reducers/reservationCateringOrdersReducer.spec.js
- app/utils/cateringUtils.js
- app/utils/cateringUtils.spec.js
> Edit catering order

- app/assets/styles/_bootstrap.scss
- app/pages/search/search-controls/_search-controls.scss
- app/shared/form-fields/_form-fields.scss
- app/shared/recurring-reservation-controls/_recurring-reservation-controls.scss
- app/shared/reservation-form/_reservation-form.scss
- package.json
Closes #268
The new version fixes error styles, so this commit reverts some fixes in commit 35a9d6d88815d87785d56710b2a9cb26276e741c.
The new version also has thicker border bottom for form fields, so this commit fixes them for some date pickers.
> Upgrade hel-bootsrap-3 version

- app/assets/styles/_application-variables.scss
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationCreateFormContainer.spec.js
- app/shared/reservation-form/ReservationForm.js
- app/shared/reservation-form/ReservationForm.spec.js
- app/shared/reservation-form/_reservation-form.scss
- app/shared/reservation-form/catering/CateringSectionContainer.js
- app/shared/reservation-form/catering/CateringSectionContainer.spec.js
- app/shared/reservation-form/catering/_catering.scss
Closes #235 
Merge #271 first.
> No recurring reservation with catering order

- app/shared/form-fields/resource-field/ResourceField.js
- app/shared/form-fields/resource-field/ResourceField.spec.js
- app/shared/form-fields/resource-field/resource-field.scss
- app/shared/form-fields/resource-field/resource-selector/ResourceItem.js
- app/shared/form-fields/resource-field/resource-selector/ResourceItem.spec.js
- app/shared/form-fields/resource-field/resource-selector/ResourceSelector.js
- app/shared/form-fields/resource-field/resource-selector/ResourceSelector.spec.js
- app/shared/form-fields/resource-field/resource-selector/resourceSelectorSelector.js
- app/shared/form-fields/resource-field/resource-selector/resourceSelectorSelector.spec.js
- app/shared/modals/resource-selector/ResourceSelectorModal.js
- app/shared/modals/resource-selector/ResourceSelectorModal.spec.js
- app/shared/modals/resource-selector/ResourceSelectorModalContainer.js
- app/shared/modals/resource-selector/ResourceSelectorModalContainer.spec.js
- app/shared/reservation-form/ReservationEditFormContainer.js
- app/shared/reservation-form/ReservationEditFormContainer.spec.js
- app/shared/reservation-form/ReservationForm.js
- app/shared/reservation-form/ReservationForm.spec.js
> Don't allow bad provider

- app/api/utils.js
- app/api/utils.spec.js
- app/shared/compact-reservation-list/compact-reservation-list.scss
- app/shared/modals/reservation-success/ReservationSuccessModal.js
- app/shared/modals/reservation-success/ReservationSuccessModal.spec.js
- app/shared/modals/reservation-success/ReservationSuccessModalContainer.js
- app/shared/modals/reservation-success/_reservation-success.scss
- app/shared/modals/reservation-success/reservationSuccessModalSelector.js
- app/shared/modals/reservation-success/reservationSuccessModalSelector.spec.js
- app/shared/reservation-form/ReservationCreateFormContainer.js
- app/shared/reservation-form/ReservationEditFormContainer.js
- app/state/reducers/reservationSuccessModalReducer.js
- app/state/reducers/reservationSuccessModalReducer.spec.js
> Show catering order success

- app/shared/reservation-details-report-button/ReservationDetailsReportButton.js
- app/shared/reservation-details-report-button/ReservationDetailsReportButton.spec.js
- app/shared/resource-daily-report-button/ResourceDailyReportButton.js
- app/shared/resource-daily-report-button/ResourceDailyReportButton.spec.js
> Make report buttons dropdown buttons

- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
> Show invoicing data in modal

- app/shared/form-fields/ReduxFormField.js
- app/shared/form-fields/ReduxFormField.spec.js
- app/shared/form-fields/Time.js
- app/shared/form-fields/Time.spec.js
- app/shared/reservation-form/catering/catering-form/CateringForm.js
- app/shared/reservation-form/catering/catering-form/CateringForm.spec.js
- app/shared/reservation-form/catering/catering-form/ServingTimeField.js
- app/shared/reservation-form/catering/catering-form/ServingTimeField.spec.js
- app/shared/reservation-form/catering/catering-form/_catering-menu-items.scss
This should make serving time work in IE which does not support <input type="time”>.
Closes #283
> Make ServingTimeField use Time field

- app/shared/comments/CommentForm.js
> Change button order

- app/shared/availability-view/_availability-view.scss
> Fix sticky time row visibility

- app/shared/availability-view/Sidebar/GroupInfo/AvailabilityViewResourceInfo/AvailabilityViewResourceInfoContainer.js
- app/shared/availability-view/Sidebar/GroupInfo/AvailabilityViewResourceInfo/AvailabilityViewResourceInfoContainer.spec.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js
- app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.spec.js
> Check correct resource permissions

- app/api/actions/utils.js
- package.json
Closes #287 
Tested with IE 11, Chrome, Firefox.
> Fix report downloading in IE

- app/shared/availability-view/_availability-view.scss
> Fix timeline slot icons on hover

- app/shared/availability-view/_availability-view.scss
> Fix showing current time on timeline

- app/shared/modals/reservation-info/ReservationInfo.js
- app/shared/modals/reservation-info/ReservationInfo.spec.js
- app/shared/reservation-form/catering/catering-form/CateringForm.js
- app/shared/reservation-form/catering/catering-form/CateringForm.spec.js
> Rename invoicing data label and make it text area (refs )

- app/shared/availability-view/_availability-view.scss
> Remove icon underline in IE
